### ISSUE TITLE
Cannot Find NodeXL Basic On windows10 After Installation successfully

### ISSUE THREAD

**Issue by Rem-Yin** [SMRFoundation/NodeXLBasic#395]
I download the NodeXL Basic from the website here: https://www.nodexlgraphgallery.org/Pages/RegistrationBasic.aspx

But I can't find “NodeXL Basic” in start menu when the installation is complete.

How could i fix it?

**Comment by arber** [comment]
Hello,

Please search for "NodeXL Excel Template" in the application list in "Start Menu"

Regards,
Arber

**Comment by Rem-Yin** [comment]
Thanks a lot! I got it.
